### ISSUE TITLE
升级2.0.0后gateway一直提示surgio版本过低

### ISSUE THREAD

**Issue by richieliuse** [geekdada/surgio#104]
[Nest] 25507   - 07/13/2020, 4:05:20 PM   [NestFactory] Starting Nest application...
[Nest] 25507   - 07/13/2020, 4:05:21 PM   
[Nest] 25507   - 07/13/2020, 4:05:21 PM   Surgio 版本过低，请升级后重新运行！
[Nest] 25507   - 07/13/2020, 4:05:21 PM   
[Nest] 25507   - 07/13/2020, 4:05:21 PM     命令：
[Nest] 25507   - 07/13/2020, 4:05:21 PM     npm install surgio@latest
[Nest] 25507   - 07/13/2020, 4:05:21 PM   
[Nest] 25507   - 07/13/2020, 4:05:21 PM   [ExceptionHandler] Surgio 版本过低 +20ms
Error: Surgio 版本过低
    at SurgioHelper.checkCoreVersion (/home/richie/project/gitlab/surgio-rules/node_modules/@surgio/gateway/src/surgio/surgio-helper.ts:86:13)
    at SurgioHelper.init (/home/richie/project/gitlab/surgio-rules/node_modules/@surgio/gateway/src/surgio/surgio-helper.ts:33:16)
    at InstanceWrapper.useFactory [as metatype] (/home/richie/project/gitlab/surgio-rules/node_modules/@surgio/gateway/src/surgio/surgio.module.ts:23:27)
    at Injector.instantiateClass (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/injector.js:293:55)
    at callback (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/injector.js:77:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Injector.resolveConstructorParams (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/injector.js:118:24)
    at Injector.loadInstance (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/injector.js:81:9)
    at Injector.loadProvider (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/injector.js:38:9)
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
    at /home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/instance-loader.js:28:13
    at async Promise.all (index 5)
    at InstanceLoader.createInstances (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/instance-loader.js:27:9)
    at InstanceLoader.createInstancesOfDependencies (/home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/injector/instance-loader.js:17:9)
    at /home/richie/project/gitlab/surgio-rules/node_modules/@nestjs/core/nest-factory.js:82:17

附doctor结果：
@surgio/gateway: 0.13.6
surgio: 2.0.0
node: 14.5.0 (/home/richie/.nvm/versions/node/v14.5.0/bin/node)
npx: 6.14.5
npm: 6.14.5

**Comment by geekdada** [comment]
请升级 @surgio/gateway 至最新版本
