### ISSUE TITLE
访问 now.sh 报错

### ISSUE THREAD

**Issue by callzhang** [geekdada/surgio#105]
```
[GET] /
21:30:17:89
[32m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [38;5;3m[NestFactory] [39m[32mStarting Nest application...[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33m[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33mSurgio 版本过低，请升级后重新运行！[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33m[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33m  命令：[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33m  npm install surgio@latest[39m
[33m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [33m[39m
[32m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [38;5;3m[InstanceLoader] [39m[32mPassportModule dependencies initialized[39m[38;5;3m +1ms[39m
[31m[Nest] 8   - [39m07/13/2020, 1:30:19 PM   [38;5;3m[ExceptionHandler] [39m[31mSurgio 版本过低[39m[38;5;3m +1ms[39m
Error: Surgio 版本过低
    at SurgioHelper.checkCoreVersion (/var/task/node_modules/@surgio/gateway/dist/surgio/surgio-helper.js:75:19)
    at SurgioHelper.init (/var/task/node_modules/@surgio/gateway/dist/surgio/surgio-helper.js:33:20)
    at InstanceWrapper.useFactory [as metatype] (/var/task/node_modules/@surgio/gateway/dist/surgio/surgio.module.js:30:45)
    at Injector.instantiateClass (/var/task/node_modules/@nestjs/core/injector/injector.js:291:55)
    at callback (/var/task/node_modules/@nestjs/core/injector/injector.js:75:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (/var/task/node_modules/@nestjs/core/injector/injector.js:116:24)
    at async Injector.loadInstance (/var/task/node_modules/@nestjs/core/injector/injector.js:79:9)
    at async Injector.loadProvider (/var/task/node_modules/@nestjs/core/injector/injector.js:36:9)
    at async Promise.all (index 4)
    at async InstanceLoader.createInstancesOfProviders (/var/task/node_modules/@nestjs/core/injector/instance-loader.js:41:9)
    at async /var/task/node_modules/@nestjs/core/injector/instance-loader.js:27:13
    at async Promise.all (index 5)
    at async InstanceLoader.createInstances (/var/task/node_modules/@nestjs/core/injector/instance-loader.js:26:9)
    at async InstanceLoader.createInstancesOfDependencies (/var/task/node_modules/@nestjs/core/injector/instance-loader.js:16:9)
    at async /var/task/node_modules/@nestjs/core/nest-factory.js:81:17
RequestId: e66817a7-ba2c-4686-a066-d9855335ef9b Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

运行doctor后发现是最新版本：
```
$ npx surgio doctor                                                                                                                                                                                       
@surgio/gateway: 0.7.0
surgio: 2.0.0
node: 14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
npx: 6.14.4
yarn: 1.19.1
npm: 6.14.4
```

**Comment by geekdada** [comment]
Duplicate #104
