### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by huangyafei** [geekdada/surgio#112]
运行 `vercel --prod` 开始 Build

结果：

> Error! Build failed
Error! Check your logs at https://******.vercel.app/_logs or run `vercel logs ******.vercel.app`

查看日志 `vercel logs ******.vercel.app`

结果：

> Fetched deployment "******.vercel.app" in *** [1s]
2020-08-06T10:03:26.475Z  [now] [mutex] command is "install"
2020-08-06T10:03:26.475Z  [now] [mutex] trying to acquire for 184
2020-08-06T10:03:26.479Z  [now] [mutex] running instance 184
2020-08-06T10:03:26.628Z  yarn add v1.22.4
2020-08-06T10:03:26.644Z  info No lockfile found.
2020-08-06T10:03:26.663Z  [1/4] Resolving packages...
2020-08-06T10:03:26.774Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:26.774Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:26.774Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:28.784Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:28.844Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:28.844Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:28.844Z  [now] [mutex] command is "install"
2020-08-06T10:03:28.844Z  [now] [mutex] trying to acquire for 216
2020-08-06T10:03:28.848Z  [now] [mutex] running instance 216
2020-08-06T10:03:28.999Z  yarn add v1.22.4
2020-08-06T10:03:29.016Z  info No lockfile found.
2020-08-06T10:03:29.035Z  [1/4] Resolving packages...
2020-08-06T10:03:29.138Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:29.138Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:29.138Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:30.148Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:30.208Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:30.208Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:30.208Z  [now] [mutex] command is "install"
2020-08-06T10:03:30.208Z  [now] [mutex] trying to acquire for 248
2020-08-06T10:03:30.213Z  [now] [mutex] running instance 248
2020-08-06T10:03:30.362Z  yarn add v1.22.4
2020-08-06T10:03:30.378Z  info No lockfile found.
2020-08-06T10:03:30.397Z  [1/4] Resolving packages...
2020-08-06T10:03:30.498Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:30.499Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:30.499Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:31.508Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:31.567Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:31.567Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:31.568Z  [now] [mutex] command is "install"
2020-08-06T10:03:31.568Z  [now] [mutex] trying to acquire for 281
2020-08-06T10:03:31.572Z  [now] [mutex] running instance 281
2020-08-06T10:03:31.721Z  yarn add v1.22.4
2020-08-06T10:03:31.736Z  info No lockfile found.
2020-08-06T10:03:31.755Z  [1/4] Resolving packages...
2020-08-06T10:03:31.860Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:31.860Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:31.861Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:33.869Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:33.929Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:33.929Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:33.929Z  [now] [mutex] command is "install"
2020-08-06T10:03:33.929Z  [now] [mutex] trying to acquire for 313
2020-08-06T10:03:33.933Z  [now] [mutex] running instance 313
2020-08-06T10:03:34.082Z  yarn add v1.22.4
2020-08-06T10:03:34.097Z  info No lockfile found.
2020-08-06T10:03:34.116Z  [1/4] Resolving packages...
2020-08-06T10:03:34.216Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:34.216Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:34.216Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:36.226Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:36.285Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:36.286Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:36.286Z  [now] [mutex] command is "install"
2020-08-06T10:03:36.286Z  [now] [mutex] trying to acquire for 345
2020-08-06T10:03:36.290Z  [now] [mutex] running instance 345
2020-08-06T10:03:36.438Z  yarn add v1.22.4
2020-08-06T10:03:36.453Z  info No lockfile found.
2020-08-06T10:03:36.472Z  [1/4] Resolving packages...
2020-08-06T10:03:36.583Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:36.583Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:36.583Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:37.592Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:37.651Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:37.651Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:37.651Z  [now] [mutex] command is "install"
2020-08-06T10:03:37.651Z  [now] [mutex] trying to acquire for 377
2020-08-06T10:03:37.656Z  [now] [mutex] running instance 377
2020-08-06T10:03:37.804Z  yarn add v1.22.4
2020-08-06T10:03:37.819Z  info No lockfile found.
2020-08-06T10:03:37.838Z  [1/4] Resolving packages...
2020-08-06T10:03:37.940Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:37.940Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:37.940Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:39.950Z  yarn add @vercel/build-utils@latest, @now/build-utils@latest...
2020-08-06T10:03:40.009Z  [now] [mutex] process.argv is ["/node12/bin/node","/vercel/.yarn/bin/yarn.js","--prod","--cwd","/vercel/7c32e42b/.build-utils","add","@vercel/build-utils@latest","@now/build-utils@latest"]
2020-08-06T10:03:40.009Z  [now] [mutex] process.cwd is "/vercel/7c32e42b/.build-utils"
2020-08-06T10:03:40.010Z  [now] [mutex] command is "install"
2020-08-06T10:03:40.010Z  [now] [mutex] trying to acquire for 409
2020-08-06T10:03:40.014Z  [now] [mutex] running instance 409
2020-08-06T10:03:40.163Z  yarn add v1.22.4
2020-08-06T10:03:40.179Z  info No lockfile found.
2020-08-06T10:03:40.199Z  [1/4] Resolving packages...
2020-08-06T10:03:40.316Z  error An unexpected error occurred: "https://registry.yarnpkg.com/@vercel%2fbuild-utils: Not found".
2020-08-06T10:03:40.316Z  info If you think this is a bug, please open a bug report with the information provided in "/vercel/7c32e42b/.build-utils/yarn-error.log".
2020-08-06T10:03:40.316Z  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
2020-08-06T10:03:40.324Z  Error: Exited with 1
2020-08-06T10:03:40.324Z      at ChildProcess.<anonymous> (/var/task/sandbox-worker.js:21953:21)
2020-08-06T10:03:40.324Z      at ChildProcess.emit (events.js:310:20)
2020-08-06T10:03:40.324Z      at ChildProcess.EventEmitter.emit (domain.js:482:12)
2020-08-06T10:03:40.324Z      at maybeClose (internal/child_process.js:1021:16)
2020-08-06T10:03:40.324Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-08-06T10:03:42.359Z  Done with "gateway.js"

**Comment by huangyafei** [comment]
今天再次 Build 又成功了。
